"""ratings_basicv4

Revision ID: 0208599a522a
Revises: 085403cce38e
Create Date: 2023-04-06 02:59:11.751370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0208599a522a'
down_revision = '085403cce38e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'avg_rating')
    op.drop_column('posts', 'post_total_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_total_rating', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('avg_rating', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
