"""ratings_basicv3

Revision ID: 085403cce38e
Revises: b54242f21dac
Create Date: 2023-04-06 02:53:35.514654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085403cce38e'
down_revision = 'b54242f21dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_total_rating', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_total_rating')
    # ### end Alembic commands ###
