"""tr_url

Revision ID: 12b9e9f473e4
Revises: 8bd91d494465
Create Date: 2023-04-09 12:48:53.344582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b9e9f473e4'
down_revision = '8bd91d494465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
