"""add 'done' fields

Revision ID: 2b012670335f
Revises: 02050b256105
Create Date: 2023-03-31 13:49:13.777471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b012670335f'
down_revision = '02050b256105'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('comments', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('hashtags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('hashtags', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('ratings', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'done')
    op.drop_column('posts', 'done')
    op.drop_column('hashtags', 'done')
    op.drop_column('hashtags', 'created_at')
    op.drop_column('comments', 'done')
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###
