"""create avg for rating

Revision ID: 2d4eed0506a5
Revises: c5f72f08ba30
Create Date: 2023-04-08 20:46:01.231855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4eed0506a5'
down_revision = 'c5f72f08ba30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
