"""remove_done_from_hashtag

Revision ID: 51bc812335a6
Revises: fb0288045c5c
Create Date: 2023-04-05 12:41:58.786154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bc812335a6'
down_revision = 'fb0288045c5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashtags', 'done')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashtags', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
