"""model text

Revision ID: 543a9f0146ba
Revises: d9ffa4f40725
Create Date: 2023-04-10 11:22:39.792494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543a9f0146ba'
down_revision = 'd9ffa4f40725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
