"""create avg for rating

Revision ID: 547561c5e194
Revises: e1d6767e05ca
Create Date: 2023-04-08 20:59:43.185070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547561c5e194'
down_revision = 'e1d6767e05ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
