"""increase url length

Revision ID: 5997d1478345
Revises: 6e8308e59b8f
Create Date: 2023-04-10 20:18:19.662433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5997d1478345'
down_revision = '6e8308e59b8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('transform_urll', sa.Text(), nullable=True))
    op.drop_column('posts', 'transform_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('transform_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('posts', 'transform_urll')
    # ### end Alembic commands ###
