"""mdl tr_url

Revision ID: 7e20bdd26fb9
Revises: 547561c5e194
Create Date: 2023-04-09 12:28:11.892528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e20bdd26fb9'
down_revision = '547561c5e194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
