"""post public_id

Revision ID: 82eedcfb8c41
Revises: c51f72cc186d
Create Date: 2023-04-07 16:03:15.845656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82eedcfb8c41'
down_revision = 'c51f72cc186d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('public_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'public_id')
    # ### end Alembic commands ###
