"""5. Add user by default

Revision ID: 8808e61e1fac
Revises: 51bc812335a6
Create Date: 2023-04-05 13:35:51.179524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8808e61e1fac'
down_revision = '51bc812335a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
