"""upgr mdl tr_url

Revision ID: 8bd91d494465
Revises: 7e20bdd26fb9
Create Date: 2023-04-09 12:33:36.780706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd91d494465'
down_revision = '7e20bdd26fb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
