"""change back to url

Revision ID: 9467ecb82664
Revises: 5997d1478345
Create Date: 2023-04-10 20:20:15.212750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9467ecb82664'
down_revision = '5997d1478345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('transform_url', sa.Text(), nullable=True))
    op.drop_column('posts', 'transform_urll')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('transform_urll', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'transform_url')
    # ### end Alembic commands ###
