"""ratings_basic

Revision ID: b54242f21dac
Revises: 9c76efa26fd1
Create Date: 2023-04-06 02:20:31.032016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54242f21dac'
down_revision = '9c76efa26fd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'rate',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'rate',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
