"""ratings_basicv5

Revision ID: cab5ce5db318
Revises: 0208599a522a
Create Date: 2023-04-06 03:08:18.784385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab5ce5db318'
down_revision = '0208599a522a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

