"""model binary

Revision ID: d11c46627ffb
Revises: 543a9f0146ba
Create Date: 2023-04-10 11:33:52.529884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11c46627ffb'
down_revision = '543a9f0146ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
