"""tr_url

Revision ID: d9ffa4f40725
Revises: 12b9e9f473e4
Create Date: 2023-04-09 13:02:07.533575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ffa4f40725'
down_revision = '12b9e9f473e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
