"""create avg for rating

Revision ID: e1d6767e05ca
Revises: 2d4eed0506a5
Create Date: 2023-04-08 20:50:48.846071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d6767e05ca'
down_revision = '2d4eed0506a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
